var classes = [
    {
        "name": "Home\\AbstractBaseController",
        "interface": false,
        "abstract": true,
        "methods": [
            {
                "name": "setParams",
                "role": "setter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "setContainer",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "hasParam",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getParam",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getParams",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "get",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "render",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "redirect",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "checkAccess",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 9,
        "nbMethods": 7,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 7,
        "nbMethodsGetter": 1,
        "nbMethodsSetters": 1,
        "wmc": 22,
        "ccn": 14,
        "ccnMethodMax": 10,
        "externals": [
            "Home\\Container",
            "Bc\\Exceptions\\MissingRequestedParam"
        ],
        "parents": [],
        "lcom": 1,
        "length": 118,
        "vocabulary": 43,
        "volume": 640.3,
        "difficulty": 14.9,
        "effort": 9542.52,
        "level": 0.07,
        "bugs": 0.21,
        "time": 530,
        "intelligentContent": 42.96,
        "number_operators": 41,
        "number_operands": 77,
        "number_operators_unique": 12,
        "number_operands_unique": 31,
        "cloc": 10,
        "loc": 71,
        "lloc": 61,
        "mi": 66.98,
        "mIwoC": 39.52,
        "commentWeight": 27.46,
        "kanDefect": 0.5,
        "relativeStructuralComplexity": 25,
        "relativeDataComplexity": 1.15,
        "relativeSystemComplexity": 26.15,
        "totalStructuralComplexity": 225,
        "totalDataComplexity": 10.33,
        "totalSystemComplexity": 235.33,
        "package": "Home\\",
        "pageRank": 0.04,
        "afferentCoupling": 0,
        "efferentCoupling": 2,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "Home\\Application",
        "interface": false,
        "abstract": false,
        "methods": [
            {
                "name": "run",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "initRequest",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "initServices",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "initDbConnection",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "initTemplateEngine",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "processRequest",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "initConfig",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "printTemplate",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 8,
        "nbMethods": 8,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 8,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 11,
        "ccn": 4,
        "ccnMethodMax": 3,
        "externals": [
            "Home\\Request",
            "Home\\ServicesStore",
            "Bc\\Exceptions\\ServiceNotFoundException",
            "serviceClassName",
            "Home\\PdoMysqlAdapter",
            "Twig_Loader_Filesystem",
            "Twig_Environment",
            "Twig\\Extension\\DebugExtension",
            "Home\\Container",
            "Home\\FrontController"
        ],
        "parents": [],
        "lcom": 1,
        "length": 80,
        "vocabulary": 27,
        "volume": 380.39,
        "difficulty": 6.7,
        "effort": 2550.35,
        "level": 0.15,
        "bugs": 0.13,
        "time": 142,
        "intelligentContent": 56.74,
        "number_operators": 21,
        "number_operands": 59,
        "number_operators_unique": 5,
        "number_operands_unique": 22,
        "cloc": 34,
        "loc": 100,
        "lloc": 66,
        "mi": 80.97,
        "mIwoC": 41.7,
        "commentWeight": 39.27,
        "kanDefect": 0.45,
        "relativeStructuralComplexity": 225,
        "relativeDataComplexity": 0.07,
        "relativeSystemComplexity": 225.07,
        "totalStructuralComplexity": 1800,
        "totalDataComplexity": 0.56,
        "totalSystemComplexity": 1800.56,
        "package": "Home\\",
        "pageRank": 0.04,
        "afferentCoupling": 0,
        "efferentCoupling": 10,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "Home\\AuthentificationSession",
        "interface": false,
        "abstract": false,
        "methods": [
            {
                "name": "isAuthenticated",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "destroyAuthSession",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "saveSession",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getCurrentUser",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 4,
        "nbMethods": 4,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 4,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 5,
        "ccn": 2,
        "ccnMethodMax": 2,
        "externals": [
            "Home\\User"
        ],
        "parents": [],
        "lcom": 1,
        "length": 20,
        "vocabulary": 7,
        "volume": 56.15,
        "difficulty": 5.63,
        "effort": 315.83,
        "level": 0.18,
        "bugs": 0.02,
        "time": 18,
        "intelligentContent": 9.98,
        "number_operators": 5,
        "number_operands": 15,
        "number_operators_unique": 3,
        "number_operands_unique": 4,
        "cloc": 7,
        "loc": 31,
        "lloc": 24,
        "mi": 90.95,
        "mIwoC": 57.37,
        "commentWeight": 33.57,
        "kanDefect": 0.22,
        "relativeStructuralComplexity": 4,
        "relativeDataComplexity": 1.08,
        "relativeSystemComplexity": 5.08,
        "totalStructuralComplexity": 16,
        "totalDataComplexity": 4.33,
        "totalSystemComplexity": 20.33,
        "package": "Home\r\\",
        "pageRank": 0.04,
        "afferentCoupling": 0,
        "efferentCoupling": 1,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "Home\\Container",
        "interface": false,
        "abstract": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "get",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "has",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 3,
        "nbMethods": 3,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 3,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 3,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "Psr\\Container\\ContainerInterface",
            "Home\\ServicesStore"
        ],
        "parents": [],
        "lcom": 1,
        "length": 12,
        "vocabulary": 5,
        "volume": 27.86,
        "difficulty": 3,
        "effort": 83.59,
        "level": 0.33,
        "bugs": 0.01,
        "time": 5,
        "intelligentContent": 9.29,
        "number_operators": 3,
        "number_operands": 9,
        "number_operators_unique": 2,
        "number_operands_unique": 3,
        "cloc": 20,
        "loc": 37,
        "lloc": 17,
        "mi": 108.32,
        "mIwoC": 62.91,
        "commentWeight": 45.41,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 4,
        "relativeDataComplexity": 1,
        "relativeSystemComplexity": 5,
        "totalStructuralComplexity": 12,
        "totalDataComplexity": 3,
        "totalSystemComplexity": 15,
        "package": "Home\\",
        "pageRank": 0.13,
        "afferentCoupling": 3,
        "efferentCoupling": 2,
        "instability": 0.4,
        "violations": {}
    },
    {
        "name": "Home\\FrontController",
        "interface": false,
        "abstract": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "setControllerName",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "setActionName",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getParams",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "setParams",
                "role": "setter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getControllerName",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getActionName",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "createConroller",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "dispatch",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 9,
        "nbMethods": 5,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 5,
        "nbMethodsGetter": 3,
        "nbMethodsSetters": 1,
        "wmc": 14,
        "ccn": 6,
        "ccnMethodMax": 3,
        "externals": [
            "Home\\Container",
            "Bc\\Exceptions\\ControllerNotFoundException",
            "className",
            "Bc\\Exceptions\\MethodActionNotFoundException",
            "Bc\\Exceptions\\MissingControllerActionResponse"
        ],
        "parents": [],
        "lcom": 1,
        "length": 73,
        "vocabulary": 20,
        "volume": 315.5,
        "difficulty": 6.38,
        "effort": 2011.32,
        "level": 0.16,
        "bugs": 0.11,
        "time": 112,
        "intelligentContent": 49.49,
        "number_operators": 22,
        "number_operands": 51,
        "number_operators_unique": 4,
        "number_operands_unique": 16,
        "cloc": 5,
        "loc": 72,
        "lloc": 67,
        "mi": 61.71,
        "mIwoC": 41.86,
        "commentWeight": 19.85,
        "kanDefect": 0.5,
        "relativeStructuralComplexity": 64,
        "relativeDataComplexity": 0.63,
        "relativeSystemComplexity": 64.63,
        "totalStructuralComplexity": 576,
        "totalDataComplexity": 5.67,
        "totalSystemComplexity": 581.67,
        "package": "Home\\",
        "pageRank": 0.05,
        "afferentCoupling": 1,
        "efferentCoupling": 5,
        "instability": 0.83,
        "violations": {}
    },
    {
        "name": "Home\\Input",
        "interface": false,
        "abstract": false,
        "methods": [
            {
                "name": "__construct",
                "role": "setter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "addValidator",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "addFilter",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "applyFilters",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "isValid",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getName",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "setValue",
                "role": "setter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getValue",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getErrorMessages",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 9,
        "nbMethods": 5,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 5,
        "nbMethodsGetter": 2,
        "nbMethodsSetters": 2,
        "wmc": 12,
        "ccn": 4,
        "ccnMethodMax": 3,
        "externals": [
            "Bc\\Validators\\InputValidatorInterface",
            "Bc\\Filters\\InputFilterInterface"
        ],
        "parents": [],
        "lcom": 1,
        "length": 47,
        "vocabulary": 10,
        "volume": 156.13,
        "difficulty": 10.67,
        "effort": 1665.39,
        "level": 0.09,
        "bugs": 0.05,
        "time": 93,
        "intelligentContent": 14.64,
        "number_operators": 15,
        "number_operands": 32,
        "number_operators_unique": 4,
        "number_operands_unique": 6,
        "cloc": 3,
        "loc": 59,
        "lloc": 56,
        "mi": 63.08,
        "mIwoC": 45.97,
        "commentWeight": 17.11,
        "kanDefect": 0.68,
        "relativeStructuralComplexity": 16,
        "relativeDataComplexity": 1.49,
        "relativeSystemComplexity": 17.49,
        "totalStructuralComplexity": 144,
        "totalDataComplexity": 13.4,
        "totalSystemComplexity": 157.4,
        "package": "Home\\",
        "pageRank": 0.09,
        "afferentCoupling": 1,
        "efferentCoupling": 2,
        "instability": 0.67,
        "violations": {}
    },
    {
        "name": "Home\\InputCollection",
        "interface": false,
        "abstract": false,
        "methods": [
            {
                "name": "addInput",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "addInputs",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getInput",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "isValid",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getErrors",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "addError",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "setValue",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getValue",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getErrorMassages",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getValues",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 10,
        "nbMethods": 9,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 9,
        "nbMethodsGetter": 1,
        "nbMethodsSetters": 0,
        "wmc": 16,
        "ccn": 7,
        "ccnMethodMax": 3,
        "externals": [
            "Home\\Input",
            "Bc\\Exceptions\\FormInputNotFoundException"
        ],
        "parents": [],
        "lcom": 1,
        "length": 72,
        "vocabulary": 17,
        "volume": 294.3,
        "difficulty": 11.25,
        "effort": 3310.84,
        "level": 0.09,
        "bugs": 0.1,
        "time": 184,
        "intelligentContent": 26.16,
        "number_operators": 18,
        "number_operands": 54,
        "number_operators_unique": 5,
        "number_operands_unique": 12,
        "cloc": 0,
        "loc": 65,
        "lloc": 65,
        "mi": 42.23,
        "mIwoC": 42.23,
        "commentWeight": 0,
        "kanDefect": 1.21,
        "relativeStructuralComplexity": 81,
        "relativeDataComplexity": 0.78,
        "relativeSystemComplexity": 81.78,
        "totalStructuralComplexity": 810,
        "totalDataComplexity": 7.8,
        "totalSystemComplexity": 817.8,
        "package": "Home\\",
        "pageRank": 0.04,
        "afferentCoupling": 0,
        "efferentCoupling": 2,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "Home\\PdoMysqlAdapter",
        "interface": false,
        "abstract": false,
        "methods": [
            {
                "name": "__construct",
                "role": "setter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "createConnection",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "execute",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "executeQuery",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "executeUpdate",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 5,
        "nbMethods": 4,
        "nbMethodsPrivate": 1,
        "nbMethodsPublic": 3,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 1,
        "wmc": 10,
        "ccn": 6,
        "ccnMethodMax": 5,
        "externals": [
            "Home\\DbAdapterInterface",
            "PDO",
            "self",
            "Bc\\Exceptions\\DatabaseErrorException"
        ],
        "parents": [],
        "lcom": 2,
        "length": 81,
        "vocabulary": 25,
        "volume": 376.15,
        "difficulty": 9.47,
        "effort": 3563.55,
        "level": 0.11,
        "bugs": 0.13,
        "time": 198,
        "intelligentContent": 39.7,
        "number_operators": 21,
        "number_operands": 60,
        "number_operators_unique": 6,
        "number_operands_unique": 19,
        "cloc": 5,
        "loc": 47,
        "lloc": 42,
        "mi": 69.95,
        "mIwoC": 45.75,
        "commentWeight": 24.2,
        "kanDefect": 0.59,
        "relativeStructuralComplexity": 36,
        "relativeDataComplexity": 0.89,
        "relativeSystemComplexity": 36.89,
        "totalStructuralComplexity": 180,
        "totalDataComplexity": 4.43,
        "totalSystemComplexity": 184.43,
        "package": "Home\\",
        "pageRank": 0.05,
        "afferentCoupling": 1,
        "efferentCoupling": 4,
        "instability": 0.8,
        "violations": {}
    },
    {
        "name": "Home\\Request",
        "interface": false,
        "abstract": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getRequestPath",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getRequestParams",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getBaseUrl",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "setRequestPath",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "setRequestParams",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 6,
        "nbMethods": 3,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 3,
        "nbMethodsGetter": 3,
        "nbMethodsSetters": 0,
        "wmc": 8,
        "ccn": 3,
        "ccnMethodMax": 3,
        "externals": [],
        "parents": [],
        "lcom": 1,
        "length": 39,
        "vocabulary": 14,
        "volume": 148.49,
        "difficulty": 4.8,
        "effort": 712.74,
        "level": 0.21,
        "bugs": 0.05,
        "time": 40,
        "intelligentContent": 30.93,
        "number_operators": 15,
        "number_operands": 24,
        "number_operators_unique": 4,
        "number_operands_unique": 10,
        "cloc": 18,
        "loc": 56,
        "lloc": 38,
        "mi": 88.41,
        "mIwoC": 49.93,
        "commentWeight": 38.48,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 4,
        "relativeDataComplexity": 1,
        "relativeSystemComplexity": 5,
        "totalStructuralComplexity": 24,
        "totalDataComplexity": 6,
        "totalSystemComplexity": 30,
        "package": "Home\\",
        "pageRank": 0.05,
        "afferentCoupling": 1,
        "efferentCoupling": 0,
        "instability": 0,
        "violations": {}
    },
    {
        "name": "Home\\ServicesStore",
        "interface": false,
        "abstract": false,
        "methods": [
            {
                "name": "offsetExists",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "offsetGet",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "offsetSet",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "offsetUnset",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "append",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 5,
        "nbMethods": 5,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 5,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 9,
        "ccn": 5,
        "ccnMethodMax": 3,
        "externals": [
            "ArrayAccess",
            "Bc\\Exceptions\\ServiceNotFoundException",
            "factoryClassName"
        ],
        "parents": [],
        "lcom": 1,
        "length": 47,
        "vocabulary": 11,
        "volume": 162.59,
        "difficulty": 7.13,
        "effort": 1158.48,
        "level": 0.14,
        "bugs": 0.05,
        "time": 64,
        "intelligentContent": 22.82,
        "number_operators": 9,
        "number_operands": 38,
        "number_operators_unique": 3,
        "number_operands_unique": 8,
        "cloc": 9,
        "loc": 46,
        "lloc": 37,
        "mi": 81.28,
        "mIwoC": 49.64,
        "commentWeight": 31.64,
        "kanDefect": 0.59,
        "relativeStructuralComplexity": 9,
        "relativeDataComplexity": 0.8,
        "relativeSystemComplexity": 9.8,
        "totalStructuralComplexity": 45,
        "totalDataComplexity": 4,
        "totalSystemComplexity": 49,
        "package": "Home\\",
        "pageRank": 0.23,
        "afferentCoupling": 2,
        "efferentCoupling": 3,
        "instability": 0.6,
        "violations": {}
    },
    {
        "name": "Home\\User",
        "interface": false,
        "abstract": false,
        "methods": [
            {
                "name": "getUsername",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "setUsername",
                "role": "setter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getId",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "setId",
                "role": "setter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "extract",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 5,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 2,
        "nbMethodsSetters": 2,
        "wmc": 5,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [],
        "parents": [],
        "lcom": 2,
        "length": 14,
        "vocabulary": 5,
        "volume": 32.51,
        "difficulty": 3,
        "effort": 97.52,
        "level": 0.33,
        "bugs": 0.01,
        "time": 5,
        "intelligentContent": 10.84,
        "number_operators": 5,
        "number_operands": 9,
        "number_operators_unique": 2,
        "number_operands_unique": 3,
        "cloc": 23,
        "loc": 49,
        "lloc": 26,
        "mi": 102.06,
        "mIwoC": 58.41,
        "commentWeight": 43.65,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 3.4,
        "relativeSystemComplexity": 3.4,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 17,
        "totalSystemComplexity": 17,
        "package": "Home\r\\",
        "pageRank": 0.15,
        "afferentCoupling": 1,
        "efferentCoupling": 0,
        "instability": 0,
        "violations": {}
    }
]